/* This file is autogenerated. Do not edit, delete, or modify this file.
 * Changes will be lost and may result in corrupted data.
 */

using System;
using System.Collections.Generic;
using WinUICommunity;

namespace WinUICommunityGallery;
public partial class BreadcrumbPageMappings
{
    public static Dictionary<Type, BreadcrumbPageConfig> PageDictionary = new()
    {
    };
}
