/* This file is autogenerated. Do not edit, delete, or modify this file.
 * Changes will be lost and may result in corrupted data.
 */

using System;
using System.Collections.Generic;

namespace WinUICommunityGallery;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"WinUICommunityGallery.Pages.TiledImageBrushPage", typeof(WinUICommunityGallery.Pages.TiledImageBrushPage)},
        {"WinUICommunityGallery.Pages.OutlineTextControlPage", typeof(WinUICommunityGallery.Pages.OutlineTextControlPage)},
        {"WinUICommunityGallery.Pages.WatermarkPage", typeof(WinUICommunityGallery.Pages.WatermarkPage)},
        {"WinUICommunityGallery.Pages.BlurAnimationPage", typeof(WinUICommunityGallery.Pages.BlurAnimationPage)},
        {"WinUICommunityGallery.Pages.TextMorphEffectPage", typeof(WinUICommunityGallery.Pages.TextMorphEffectPage)},
        {"WinUICommunityGallery.Pages.TextGlitchEffectPage", typeof(WinUICommunityGallery.Pages.TextGlitchEffectPage)},
        {"WinUICommunityGallery.Pages.TextBlockStrokeViewPage", typeof(WinUICommunityGallery.Pages.TextBlockStrokeViewPage)},
        {"WinUICommunityGallery.Pages.ParticlePage", typeof(WinUICommunityGallery.Pages.ParticlePage)},
        {"WinUICommunityGallery.Pages.WaveCirclePage", typeof(WinUICommunityGallery.Pages.WaveCirclePage)},
        {"WinUICommunityGallery.Pages.BubblePage", typeof(WinUICommunityGallery.Pages.BubblePage)},
        {"WinUICommunityGallery.Pages.GooeyPage", typeof(WinUICommunityGallery.Pages.GooeyPage)},
        {"WinUICommunityGallery.Pages.PinBoxPage", typeof(WinUICommunityGallery.Pages.PinBoxPage)},
        {"WinUICommunityGallery.Pages.SelectorBarSegmentedPage", typeof(WinUICommunityGallery.Pages.SelectorBarSegmentedPage)},
        {"WinUICommunityGallery.Pages.ColorfulShimmingEffectPage", typeof(WinUICommunityGallery.Pages.ColorfulShimmingEffectPage)},
        {"WinUICommunityGallery.Pages.LongShadowTextBlockPage", typeof(WinUICommunityGallery.Pages.LongShadowTextBlockPage)},
        {"WinUICommunityGallery.Pages.CredentialHelperPage", typeof(WinUICommunityGallery.Pages.CredentialHelperPage)},
        {"WinUICommunityGallery.Pages.CompositionHelperPage", typeof(WinUICommunityGallery.Pages.CompositionHelperPage)},
        {"WinUICommunityGallery.Pages.FlipSidePage", typeof(WinUICommunityGallery.Pages.FlipSidePage)},
        {"WinUICommunityGallery.Pages.PagerControlPage", typeof(WinUICommunityGallery.Pages.PagerControlPage)},
        {"WinUICommunityGallery.Pages.AutoScrollViewPage", typeof(WinUICommunityGallery.Pages.AutoScrollViewPage)},
        {"WinUICommunityGallery.Pages.OpacityMaskViewPage", typeof(WinUICommunityGallery.Pages.OpacityMaskViewPage)},
        {"WinUICommunityGallery.Pages.ProgressBarPage", typeof(WinUICommunityGallery.Pages.ProgressBarPage)},
        {"WinUICommunityGallery.Pages.DividerPage", typeof(WinUICommunityGallery.Pages.DividerPage)},
        {"WinUICommunityGallery.Pages.ShieldPage", typeof(WinUICommunityGallery.Pages.ShieldPage)},
        {"WinUICommunityGallery.Pages.GravatarPage", typeof(WinUICommunityGallery.Pages.GravatarPage)},
        {"WinUICommunityGallery.Pages.GrowlPage", typeof(WinUICommunityGallery.Pages.GrowlPage)},
        {"WinUICommunityGallery.Pages.OptionsPageControlPage", typeof(WinUICommunityGallery.Pages.OptionsPageControlPage)},
        {"WinUICommunityGallery.Pages.RainbowFramePage", typeof(WinUICommunityGallery.Pages.RainbowFramePage)},
        {"WinUICommunityGallery.Pages.FileAndFolderPickerPage", typeof(WinUICommunityGallery.Pages.FileAndFolderPickerPage)},
        {"WinUICommunityGallery.Pages.StylesPage", typeof(WinUICommunityGallery.Pages.StylesPage)},
        {"WinUICommunityGallery.Pages.SwitchPresenterPage", typeof(WinUICommunityGallery.Pages.SwitchPresenterPage)},
        {"WinUICommunityGallery.Pages.ValidationPage", typeof(WinUICommunityGallery.Pages.ValidationPage)},
        {"WinUICommunityGallery.Pages.ExtensionPage", typeof(WinUICommunityGallery.Pages.ExtensionPage)},
        {"WinUICommunityGallery.Pages.ThemeManagerPage", typeof(WinUICommunityGallery.Pages.ThemeManagerPage)},
        {"WinUICommunityGallery.Pages.NavigationManagerPage", typeof(WinUICommunityGallery.Pages.NavigationManagerPage)},
        {"WinUICommunityGallery.Pages.PrintPage", typeof(WinUICommunityGallery.Pages.PrintPage)},
        {"WinUICommunityGallery.Pages.ContentDialogPage", typeof(WinUICommunityGallery.Pages.ContentDialogPage)},
        {"WinUICommunityGallery.Pages.CommandObservablePage", typeof(WinUICommunityGallery.Pages.CommandObservablePage)},
        {"WinUICommunityGallery.Pages.CheckUpdatePage", typeof(WinUICommunityGallery.Pages.CheckUpdatePage)},
        {"WinUICommunityGallery.Pages.InlineAutoCompleteTextBoxPage", typeof(WinUICommunityGallery.Pages.InlineAutoCompleteTextBoxPage)},
        {"WinUICommunityGallery.Pages.AllLandingsPage", typeof(WinUICommunityGallery.Pages.AllLandingsPage)},
        {"WinUICommunityGallery.Pages.HomeLandingsPage", typeof(WinUICommunityGallery.Pages.HomeLandingsPage)},
        {"WinUICommunityGallery.Pages.SettingsGroup", typeof(WinUICommunityGallery.Pages.SettingsGroup)},
        {"WinUICommunityGallery.Pages.SettingsControls", typeof(WinUICommunityGallery.Pages.SettingsControls)},
        {"WinUICommunityGallery.Pages.GeneralPage", typeof(WinUICommunityGallery.Pages.GeneralPage)},
        {"WinUICommunityGallery.Pages.OobePage", typeof(WinUICommunityGallery.Pages.OobePage)},
        {"WinUICommunityGallery.Pages.AwakePage", typeof(WinUICommunityGallery.Pages.AwakePage)},
        {"WinUICommunityGallery.Pages.ColorPickerPage", typeof(WinUICommunityGallery.Pages.ColorPickerPage)},
        {"WinUICommunityGallery.Pages.FancyZonesPage", typeof(WinUICommunityGallery.Pages.FancyZonesPage)},
        {"WinUICommunityGallery.Pages.PowerPreviewPage", typeof(WinUICommunityGallery.Pages.PowerPreviewPage)},
        {"WinUICommunityGallery.Pages.ImageResizerPage", typeof(WinUICommunityGallery.Pages.ImageResizerPage)},
        {"WinUICommunityGallery.Pages.KeyboardManagerPage", typeof(WinUICommunityGallery.Pages.KeyboardManagerPage)},
        {"WinUICommunityGallery.Pages.PowerRenamePage", typeof(WinUICommunityGallery.Pages.PowerRenamePage)},
        {"WinUICommunityGallery.Pages.PowerLauncherPage", typeof(WinUICommunityGallery.Pages.PowerLauncherPage)},
        {"WinUICommunityGallery.Pages.ShortcutGuidePage", typeof(WinUICommunityGallery.Pages.ShortcutGuidePage)},
    };
}
