/* This file is autogenerated. Do not edit, delete, or modify this file.
 * Changes will be lost and may result in corrupted data.
 */

using System;
using System.Collections.Generic;

namespace WinUICommunityGallery;
public partial class SampleNavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"WinUICommunityGallery.Pages.CheckUpdatePage", typeof(WinUICommunityGallery.Pages.CheckUpdatePage)},
        {"WinUICommunityGallery.Pages.CommandObservablePage", typeof(WinUICommunityGallery.Pages.CommandObservablePage)},
        {"WinUICommunityGallery.Pages.ContentDialogPage", typeof(WinUICommunityGallery.Pages.ContentDialogPage)},
        {"WinUICommunityGallery.Pages.InlineAutoCompleteTextBoxPage", typeof(WinUICommunityGallery.Pages.InlineAutoCompleteTextBoxPage)},
        {"WinUICommunityGallery.Pages.SettingsControls", typeof(WinUICommunityGallery.Pages.SettingsControls)},
        {"Settings2", typeof(WinUICommunityGallery.Pages.mySectionPage)},
        {"WinUICommunityGallery.Pages.KeyboardManagerPage", typeof(WinUICommunityGallery.Pages.KeyboardManagerPage)},
        {"WinUICommunityGallery.Pages.ImageResizerPage", typeof(WinUICommunityGallery.Pages.ImageResizerPage)},
        {"WinUICommunityGallery.Pages.FancyZonesPage", typeof(WinUICommunityGallery.Pages.FancyZonesPage)},
        {"Settings3", typeof(WinUICommunityGallery.Pages.mySectionPage)},
        {"WinUICommunityGallery.Pages.OobePage", typeof(WinUICommunityGallery.Pages.OobePage)},
        {"WinUICommunityGallery.Pages.ColorPickerPage", typeof(WinUICommunityGallery.Pages.ColorPickerPage)},
        {"Settings4", typeof(WinUICommunityGallery.Pages.mySectionPage)},
        {"WinUICommunityGallery.Pages.OobePage", typeof(WinUICommunityGallery.Pages.OobePage)},
        {"WinUICommunityGallery.Pages.AwakePage", typeof(WinUICommunityGallery.Pages.AwakePage)},
    };
}
