// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace WucGalleryApp;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"WucGalleryApp.Views.TiledImageBrushPage", typeof(WucGalleryApp.Views.TiledImageBrushPage)},
        {"WucGalleryApp.Views.OutlineTextControlPage", typeof(WucGalleryApp.Views.OutlineTextControlPage)},
        {"WucGalleryApp.Views.WatermarkPage", typeof(WucGalleryApp.Views.WatermarkPage)},
        {"WucGalleryApp.Views.BlurAnimationPage", typeof(WucGalleryApp.Views.BlurAnimationPage)},
        {"WucGalleryApp.Views.TextMorphEffectPage", typeof(WucGalleryApp.Views.TextMorphEffectPage)},
        {"WucGalleryApp.Views.TextGlitchEffectPage", typeof(WucGalleryApp.Views.TextGlitchEffectPage)},
        {"WucGalleryApp.Views.TextBlockStrokeViewPage", typeof(WucGalleryApp.Views.TextBlockStrokeViewPage)},
        {"WucGalleryApp.Views.ParticlePage", typeof(WucGalleryApp.Views.ParticlePage)},
        {"WucGalleryApp.Views.WaveCirclePage", typeof(WucGalleryApp.Views.WaveCirclePage)},
        {"WucGalleryApp.Views.BubblePage", typeof(WucGalleryApp.Views.BubblePage)},
        {"WucGalleryApp.Views.GooeyPage", typeof(WucGalleryApp.Views.GooeyPage)},
        {"WucGalleryApp.Views.PinBoxPage", typeof(WucGalleryApp.Views.PinBoxPage)},
        {"WucGalleryApp.Views.SelectorBarSegmentedPage", typeof(WucGalleryApp.Views.SelectorBarSegmentedPage)},
        {"WucGalleryApp.Views.ColorfulShimmingEffectPage", typeof(WucGalleryApp.Views.ColorfulShimmingEffectPage)},
        {"WucGalleryApp.Views.LongShadowTextBlockPage", typeof(WucGalleryApp.Views.LongShadowTextBlockPage)},
        {"WucGalleryApp.Views.CredentialHelperPage", typeof(WucGalleryApp.Views.CredentialHelperPage)},
        {"WucGalleryApp.Views.CompositionHelperPage", typeof(WucGalleryApp.Views.CompositionHelperPage)},
        {"WucGalleryApp.Views.FlipSidePage", typeof(WucGalleryApp.Views.FlipSidePage)},
        {"WucGalleryApp.Views.PagerControlPage", typeof(WucGalleryApp.Views.PagerControlPage)},
        {"WucGalleryApp.Views.AutoScrollViewPage", typeof(WucGalleryApp.Views.AutoScrollViewPage)},
        {"WucGalleryApp.Views.OpacityMaskViewPage", typeof(WucGalleryApp.Views.OpacityMaskViewPage)},
        {"WucGalleryApp.Views.ProgressBarPage", typeof(WucGalleryApp.Views.ProgressBarPage)},
        {"WucGalleryApp.Views.DividerPage", typeof(WucGalleryApp.Views.DividerPage)},
        {"WucGalleryApp.Views.ShieldPage", typeof(WucGalleryApp.Views.ShieldPage)},
        {"WucGalleryApp.Views.GravatarPage", typeof(WucGalleryApp.Views.GravatarPage)},
        {"WucGalleryApp.Views.GrowlPage", typeof(WucGalleryApp.Views.GrowlPage)},
        {"WucGalleryApp.Views.OptionsPageControlPage", typeof(WucGalleryApp.Views.OptionsPageControlPage)},
        {"WucGalleryApp.Views.RainbowFramePage", typeof(WucGalleryApp.Views.RainbowFramePage)},
        {"WucGalleryApp.Views.FileAndFolderPickerPage", typeof(WucGalleryApp.Views.FileAndFolderPickerPage)},
        {"WucGalleryApp.Views.StylesPage", typeof(WucGalleryApp.Views.StylesPage)},
        {"WucGalleryApp.Views.SwitchPresenterPage", typeof(WucGalleryApp.Views.SwitchPresenterPage)},
        {"WucGalleryApp.Views.ValidationPage", typeof(WucGalleryApp.Views.ValidationPage)},
        {"WucGalleryApp.Views.ExtensionPage", typeof(WucGalleryApp.Views.ExtensionPage)},
        {"WucGalleryApp.Views.ThemeManagerPage", typeof(WucGalleryApp.Views.ThemeManagerPage)},
        {"WucGalleryApp.Views.NavigationManagerPage", typeof(WucGalleryApp.Views.NavigationManagerPage)},
        {"WucGalleryApp.Views.PrintPage", typeof(WucGalleryApp.Views.PrintPage)},
        {"WucGalleryApp.Views.ContentDialogPage", typeof(WucGalleryApp.Views.ContentDialogPage)},
        {"WucGalleryApp.Views.CommandObservablePage", typeof(WucGalleryApp.Views.CommandObservablePage)},
        {"WucGalleryApp.Views.CheckUpdatePage", typeof(WucGalleryApp.Views.CheckUpdatePage)},
        {"WucGalleryApp.Views.InlineAutoCompleteTextBoxPage", typeof(WucGalleryApp.Views.InlineAutoCompleteTextBoxPage)},
        {"WucGalleryApp.Views.AllLandingsPage", typeof(WucGalleryApp.Views.AllLandingsPage)},
        {"WucGalleryApp.Views.HomeLandingsPage", typeof(WucGalleryApp.Views.HomeLandingsPage)},
        {"WucGalleryApp.Views.SettingsGroup", typeof(WucGalleryApp.Views.SettingsGroup)},
        {"WucGalleryApp.Views.SettingsControls", typeof(WucGalleryApp.Views.SettingsControls)},
        {"WucGalleryApp.Views.GeneralPage", typeof(WucGalleryApp.Views.GeneralPage)},
        {"WucGalleryApp.Views.OobePage", typeof(WucGalleryApp.Views.OobePage)},
        {"WucGalleryApp.Views.AwakePage", typeof(WucGalleryApp.Views.AwakePage)},
        {"WucGalleryApp.Views.ColorPickerPage", typeof(WucGalleryApp.Views.ColorPickerPage)},
        {"WucGalleryApp.Views.FancyZonesPage", typeof(WucGalleryApp.Views.FancyZonesPage)},
        {"WucGalleryApp.Views.PowerPreviewPage", typeof(WucGalleryApp.Views.PowerPreviewPage)},
        {"WucGalleryApp.Views.ImageResizerPage", typeof(WucGalleryApp.Views.ImageResizerPage)},
        {"WucGalleryApp.Views.KeyboardManagerPage", typeof(WucGalleryApp.Views.KeyboardManagerPage)},
        {"WucGalleryApp.Views.PowerRenamePage", typeof(WucGalleryApp.Views.PowerRenamePage)},
        {"WucGalleryApp.Views.PowerLauncherPage", typeof(WucGalleryApp.Views.PowerLauncherPage)},
        {"WucGalleryApp.Views.ShortcutGuidePage", typeof(WucGalleryApp.Views.ShortcutGuidePage)},
    };
}
