// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace WucGalleryApp;
public partial class SampleNavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"WucGalleryApp.Views.CheckUpdatePage", typeof(WucGalleryApp.Views.CheckUpdatePage)},
        {"WucGalleryApp.Views.CommandObservablePage", typeof(WucGalleryApp.Views.CommandObservablePage)},
        {"WucGalleryApp.Views.ContentDialogPage", typeof(WucGalleryApp.Views.ContentDialogPage)},
        {"WucGalleryApp.Views.InlineAutoCompleteTextBoxPage", typeof(WucGalleryApp.Views.InlineAutoCompleteTextBoxPage)},
        {"WucGalleryApp.Views.SettingsControls", typeof(WucGalleryApp.Views.SettingsControls)},
        {"Settings2", typeof(WucGalleryApp.Views.mySectionPage)},
        {"WucGalleryApp.Views.KeyboardManagerPage", typeof(WucGalleryApp.Views.KeyboardManagerPage)},
        {"WucGalleryApp.Views.ImageResizerPage", typeof(WucGalleryApp.Views.ImageResizerPage)},
        {"WucGalleryApp.Views.FancyZonesPage", typeof(WucGalleryApp.Views.FancyZonesPage)},
        {"Settings3", typeof(WucGalleryApp.Views.mySectionPage)},
        {"WucGalleryApp.Views.OobePage", typeof(WucGalleryApp.Views.OobePage)},
        {"WucGalleryApp.Views.ColorPickerPage", typeof(WucGalleryApp.Views.ColorPickerPage)},
        {"Settings4", typeof(WucGalleryApp.Views.mySectionPage)},
        {"WucGalleryApp.Views.OobePage2", typeof(WucGalleryApp.Views.OobePage)},
        {"WucGalleryApp.Views.AwakePage", typeof(WucGalleryApp.Views.AwakePage)},
    };
}
