global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using WinUICommunity;
global using WucGalleryApp.Common;
global using WucGalleryApp.ViewModels;
global using WucGalleryApp.Views;
global using static WucGalleryApp.Common.AppHelper;
